import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from models import TestSuite

# Load OpenAI API key from .env file
load_dotenv()


def review_test_cases(file_name):
    """
    Reviews and enhances a JSON test case file using an AI agent (GPT-4o).

    The agent acts as a Senior QA Automation Architect and Security Expert,
    analyzing existing test cases, improving them, and adding missing edge cases,
    negative paths, boundary values, and basic security checks.

    Args:
        file_name (str): The name of the JSON file (e.g., 'login.json')
                         located in the '../test_cases/' directory.

    Returns:
        None: The reviewed output is saved to a new '_reviewed.json' file.
    """
    # Build the absolute path to the test_cases directory relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.abspath(os.path.join(script_dir, '..', 'test_cases', file_name))

    # Load the test cases JSON file
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            test_cases_to_review = file.read()
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return None

    # Initialize the LLM (GPT-4o) with moderate temperature for balanced creativity
    llm = ChatOpenAI(model='gpt-4o', temperature=0.3)

    # Bind the LLM to the Pydantic TestSuite model for structured JSON output
    structured_llm = llm.with_structured_output(TestSuite)

    # Define the system and user prompts for the AI review
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a Senior QA Automation Architect and Security Expert. "
                   "Your task is to perform a peer review of test cases generated by a Junior QA. "
                   "Your goal is to critically analyze the provided test cases and ENHANCE the test suite "
                   "by adding missing Edge Cases, Negative Paths, Boundary Value tests, and basic Security "
                   "checks (e.g., SQL Injection, long strings). Maintain the strict JSON structure."),
        ("user", "Review the following JSON test cases. Keep the good ones, improve them if necessary, "
                 "and ADD new robust test cases that a junior might have missed. "
                 "Return the fully updated and expanded test suite.\n\n"
                 "Junior's Test Cases:\n{test_cases_to_review}")
    ])

    # Create the chain: prompt -> LLM -> structured output
    chain = prompt | structured_llm

    print(f"Reviewer Agent is reviewing the file: {file_path}...\n")

    # Invoke the AI agent with the raw test cases content
    response = chain.invoke({"test_cases_to_review": test_cases_to_review})

    # Convert the Pydantic model response to a formatted JSON string
    json_output = response.model_dump_json(indent=4)

    # Save the reviewed test cases to a new file (e.g., login_reviewed.json)
    output_json_filename = file_name.replace('.json', '_reviewed.json')
    output_path = os.path.abspath(os.path.join(script_dir, '..', 'test_cases', output_json_filename))

    with open(output_path, 'w', encoding='utf-8') as output_file:
        output_file.write(json_output)

    print("===========================================\n")
    print("=== TEST CASES HAVE BEEN REVIEWED ===")
    print("\n===========================================")


if __name__ == "__main__":
    # Default file to review when running the script directly
    selected_file = "login.json"
    review_test_cases(selected_file)


